services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: voucher_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/voucher_store
    depends_on:
      - postgres
    ports:
      - '4000:4000'

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - '3000:3000'

volumes:
  pgdata: 
